name: Build and Commit Main Executable

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build main executable
        run: pyinstaller --onefile --windowed --name FilesByDate main.py

      - name: Move executable to bin
        run: |
          mkdir bin
          move dist\FilesByDate.exe bin\FilesByDate.exe

      - name: Commit and push executable
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/FilesByDate.exe
          git commit -m "Update FilesByDate.exe [auto-build]" || echo "No changes to commit"
          git push